"
This is deprecated class because the original class AbstractFormButtonModel was renamed to AbstractFormButtonPresenter. You should stop to use this class and modify your code to use AbstractFormButtonPresenter.
"
Class {
	#name : #AbstractFormButtonModel,
	#superclass : #AbstractFormButtonPresenter,
	#category : #'MigratorFromPharo60To70-Spec-Obsolete'
}

{ #category : #deprecation }
AbstractFormButtonModel class >> isDeprecated [
	^true
]
