"
This is deprecated class because the original class TableContainerModel was renamed to TableContainerPresenter. You should stop to use this class and modify your code to use TableContainerPresenter.
"
Class {
	#name : #TableContainerModel,
	#superclass : #TableContainerPresenter,
	#category : #'MigratorFromPharo60To70-Spec-Obsolete'
}

{ #category : #deprecation }
TableContainerModel class >> isDeprecated [
	^true
]
