"
This is deprecated class because the original class TextInputFieldModel was renamed to TextInputFieldPresenter. You should stop to use this class and modify your code to use TextInputFieldPresenter.
"
Class {
	#name : #TextInputFieldModel,
	#superclass : #TextInputFieldPresenter,
	#category : #'MigratorFromPharo60To70-Spec-Obsolete'
}

{ #category : #deprecation }
TextInputFieldModel class >> isDeprecated [
	^true
]
